### ISSUE TITLE
Metadata creation error

### ISSUE THREAD

**Issue by zarafc** [timlegge/SamlLoginContrib#6]
Hi
I have a fresh installation of Foswiki and I'm trying to use the Saml authentication

The information I have from the identity provider is the IDP Metadata URI and nothing else
Also the id provider requests the metadata from my Foswiki instance (Service Provider), which I dont have 

The directory /var/www/foswiki/saml/ and its files do not exist and if I try to 'Generate' from bin/configure  the sign_metatdata I get the error:

```
Error
Crypt::OpenSSL::X509: Failed to create BIO
```
I guess the error comes from the fact that the /var/www/foswiki/saml/  files do not exist.

How do I create these files? 

Cheers

**Comment by zarafc** [comment]
Making progress. I was able to create the 2 files with

`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout sign.key -out sign.pem`

However, I copy in the  identity Provider Root Certificate into /var/www/foswiki/saml/cacert.pem
and get the error 

`warning | Error loading file /var/www/foswiki/saml/cacert.pem: error:0B084088:x509 certificate routines:X509_load_cert_crl_file:no certificate or crl found`

Any ideas?

**Comment by zarafc** [comment]
Making progress (sorry for the noise)
My cacert.pem file was not correlty formated as shown using `openssl x509 -noout -text -in cacert.pem`

I summarize the steps needed to get this working in my case
1. Create the sign.pem and key.pem files with `openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout sign.key -out sign.pem`
2. From `bin/configure Saml->Metadata Settings` use the **Generate** button to create the metadata
3. Copy/Paste this metdata into the Identity Provider's registration
4. Copy/Paste the Identity Provider's root certificate into the `cacert.pem` file
5. Check if the files are ok with `openssl x509 -noout -text -in ` .

**Comment by timlegge** [comment]
let me look.  I don't recall how much error checking I added to that.  Are you still having the issue?

**Comment by zarafc** [comment]
Thanks for the reply.
I got this to work in the end. It is important to get the correct names of the local Attributes in order to create the WikiNames etc and also understand the `pem ` files and the order of their creation, which can be a bit fiddly. 

The NewUserPlugin is used to create user pages and the default template is LDAP, which is not enabled in my case so I changed this.

I can use the contrib to authenticate and register a user. The issue is after login there is a redirect and I get a `502 Bad gateway ` error , however if I reload the page all is well. What setting is needed to correct this?

Cheers

**Comment by timlegge** [comment]
I used to get that but I thought a version upgrade of plug-in plus latest Net::SAML2 sorted it

**Comment by timlegge** [comment]
What version of Net::SAML2 and SamlLoginContriv do you have

**Comment by zarafc** [comment]
Net::SAML2  = 0.55
SamlLoginContrib = VERSION = '1.16'; RELEASE = '05 May 2022';

It is based from the  Foswiki 2.1.7 Dockerfile

**Comment by timlegge** [comment]
In:

General settings
Web URLS and Paths (Enable Expert Settings)

Set Permitted Redirect Host Urls to the URL of the Issuer - eg https://sts.windows.net for Office 365

**Comment by zarafc** [comment]
I had set the top level domain of the Issuer and then added the full path and aliases. I get mixed results , sometimes it passes and sometimes I get the 502 bad gateway error. Maybe old Cookies or Sessions are interfering?  I will check out the correct address that is expected.

**Comment by timlegge** [comment]
Enable debugging and look at the logs.  /var/www/foswiki/working

This issue was tough to track down for me and some times depended on the page you were originally on.  Delete your cookies for the wiki site and see if you can reproduce.

**Comment by timlegge** [comment]
It should be passing the original page information in the RelayState for to the IdP and it should be returning it properly (without modification).  If you are not already using SAML Message Decoder add in for your browser please install and it will help track the session

**Comment by zarafc** [comment]
The` {PermittedRedirectHostUrls} ` included the saml IdP and was correctly set without the trainling / . I did have a trailing / on the` {Saml}{url}` , which is now corrected and I am getting better results. 

the debug.log shows the following for RealyState. Is this what is expected at login ?
```
| 2022-07-15T14:34:08+00:00 debug | SamlLoginContrib: login(): |
| 2022-07-15T14:34:08+00:00 debug |     SAML Query Parameters:  |
| 2022-07-15T14:34:08+00:00 debug |         RelayState:  |
| 2022-07-15T14:34:08+00:00 debug |         foswiki_origin: GET,view,/ |
| 2022-07-15T14:34:08+00:00 debug |     Net::SAML2::IdP created from url |
```

**Comment by timlegge** [comment]
yes, that looks fine

**Comment by timlegge** [comment]
I think this was answered
