### ISSUE TITLE
variable $idp masks earlier declaration in SamlLogin.pm

### ISSUE THREAD

**Issue by zarafc** [timlegge/SamlLoginContrib#7]
Hello

The solr indexing is failing with

```
31 -rwxr-xr-x 1 10027100 root 31619 Aug 2 12:32 /var/www/foswiki/lib/Foswiki/Users.pm
"my" variable $idp masks earlier declaration in same scope at /data/foswiki/lib/Foswiki/LoginManager/SamlLogin.pm line 881.
```

I noticed the WebChanges topics are not listing new topics. Could the above be the cause?

**Comment by timlegge** [comment]
Sorry for the delay on this.  If you are using the docker-compose it starts solr for searching and for WebChanges.  If you are not using Solr I believe WebChanges does a Search.

I will fix the error but it should not be causing this

**Comment by zarafc** [comment]
Thanks for the reply. I did see new topics in the WebChanges after the SolrFull run a few days later (this is programmed to run once a week).
